# json
POST http://localhost:8080/aes/book
Accept: application/vnd.rxcats.json
Content-Type: application/vnd.rxcats.json

{"book":{"isbn":"9780007525546","name":"반지의 제왕","author":"J. R. R. 톨킨","createdAt":"2018-10-26T08:05:57+00:00"}}

###

# json empty
POST http://localhost:8080/aes/book/empty
Accept: application/vnd.rxcats.json
Content-Type: application/vnd.rxcats.json

###

# json error
POST http://localhost:8080/aes/book/error
Accept: application/vnd.rxcats.json
Content-Type: application/vnd.rxcats.json

###



# encrypted
POST http://localhost:8080/aes/book
Accept: application/vnd.rxcats.enc
Content-Type: application/vnd.rxcats.enc

QGNzvLz/KnjIOifv+UFnUWVkPwFw52NuV4AKdZ001zTsEBHYk1X/VmHRfWB/GXszlkcHWfWvXYlADoVdja4c7ZxQivMau7MS28LK5iydBHb9VnTYnc+z9LUTrhogieHQi0mDpWJJxOqLoNlQGBYU7bbhUhYbwAXK7ZODVR7mnEE=


###

# encrypted empty
POST http://localhost:8080/aes/book/empty
Accept: application/vnd.rxcats.enc
Content-Type: application/vnd.rxcats.enc

###

# encrypted error
POST http://localhost:8080/aes/book/error
Accept: application/vnd.rxcats.enc
Content-Type: application/vnd.rxcats.enc

###



